#!/bin/sh

case "$1" in
  start)
    echo "Starting Wi-Fi AP mode..."

    killall wpa_supplicant 2>/dev/null || true
    killall hostapd 2>/dev/null || true
    killall dnsmasq 2>/dev/null || true

    ip link set wlan0 down
    ip addr flush dev wlan0
    ip addr add 192.168.88.1/24 dev wlan0
    ip link set wlan0 up

    hostapd /etc/hostapd.conf -B

    dnsmasq \
      --interface=wlan0 \
      --bind-interfaces \
      --dhcp-range=192.168.88.50,192.168.88.150,12h \
      --dhcp-option=3,192.168.88.1 \
      --dhcp-option=6,192.168.88.1
    ;;

  stop)
    killall dnsmasq 2>/dev/null || true
    killall hostapd 2>/dev/null || true
    ip addr flush dev wlan0
    ;;

  restart)
    "$0" stop
    "$0" start
    ;;
esac
